node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'cd . && python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'cd . && py.test --verbose --junit-xml test-reports/results.xml ../sources/test_calc.py'
        }
        post {
            always {
                junit 'cd . && test-reports/results.xml'
            }
        }
    }
    stage('Deliver') {
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            sh 'cd . && pyinstaller --onefile ../sources/add2vals.py'
        }
        post {
            success {
                archiveArtifacts 'dist/add2vals'
            }
        }
    }
}
