node {
    stage('Build') {
        dir('sources') {
            sh 'cd . && python -m py_compile add2vals.py calc.py'
        }
    }
    stage('Test') {
        dir('sources') {
            sh 'py.test --verbose --junit-xml test-reports/results.xml test_calc.py'
        }
        post {
            always {
                junit 'test-reports/results.xml'
            }
        }
    }
    stage('Deliver') {
        dir('sources') {
            sh 'pyinstaller --onefile add2vals.py'
        }
        post {
            success {
                archiveArtifacts 'dist/add2vals'
            }
        }
    }
}
